# Site settings
name: Pushwitha Krishnappa
title: Pushwitha Krishnappa | Portfolio
description: Driven and innovative Ph.D. student in Computer Science with a robust foundation in Artificial Intelligence and Machine Learning. Seeking to contribute advanced technical expertise and a passion for data-driven problem solving in a challenging environment. Eager to apply experience in developing cutting-edge machine learning models and insightful data analyses to create impactful solutions in a dynamic and collaborative setting.
url: https://pushwithak.github.io/
baseurl: ''
email: pushwitha.krishnappa@gmail.com
# cover: https://pushwithak.github.io/img/og.png
logo: https://pushwithak.github.io/img/emojis/technologist.png
resume: https://pushwithak.github.io/resume.pdf
social:
  - title: email
    url: mailto:pushwitha.krishnappa@gmail.com
  # - title: twitter
  #   url: https://twitter.com/username
  # - title: instagram
  #   url: https://instagram.com/username
  - title: github
    url: https://github.com/pushwithak
  - title: linkedin
    url: https://www.linkedin.com/in/pushwitha

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
